[features]
seeds = false
skip-lint = false

[programs.localnet]
rbac_system = "BngMjVQo1dM12Ra27YkujpSitndxXMcKWKvUYw4LaLWN"

[programs.devnet]
rbac_system = "BngMjVQo1dM12Ra27YkujpSitndxXMcKWKvUYw4LaLWN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.31.0"
solana_version = "1.18.18"
rust_version = "1.79.0"